spring:
  config:
    import: "configserver:" 
  datasource:
    url: jdbc:postgresql://197.254.53.252:5432/celebratedb
    username: celebrate
    password: celebrate123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://197.254.53.252:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: 197.254.53.252
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90 
