server:
  port: 8085

spring:
  application:
    name: news-feed-service
  cache:
    type: redis
  redis:
    host: 197.254.53.252
    port: 6379

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" 