server:
  port: 8087

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: 197.254.53.252:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" 