server:
  port: 8093
  address: 0.0.0.0

spring:
  application:
    name: rating-review-service

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" 