server:
  port: 8095
  host: 0.0.0.0

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://localhost:9200

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" 