import '../models/comment.dart';
import '../models/like.dart';
import '../models/user.dart';
import '../models/flick.dart';
import '../models/post.dart';
import '../models/audio_post.dart';
import 'audio_service.dart';

class SearchService {
  // Dummy user data for search
  static final List<User> dummyUsers = [
    User(
      id: 1,
      username: 'hamcurd',
      password: '',
      email: 'hamcurd@example.com',
      role: 'Celebrity',
      fullName: 'Bruam Halaberry',
      profileImageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 2,
      username: 'musicfan',
      password: '',
      email: 'musicfan@example.com',
      role: 'User',
      fullName: 'Music Fan',
      profileImageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 3,
      username: 'jazzcat',
      password: '',
      email: 'jazzcat@example.com',
      role: 'Celebrity',
      fullName: 'Jazz Cat',
      profileImageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 4,
      username: 'rockstar',
      password: '',
      email: 'rockstar@example.com',
      role: 'Celebrity',
      fullName: 'Rock Star',
      profileImageUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 5,
      username: 'popqueen',
      password: '',
      email: 'popqueen@example.com',
      role: 'Celebrity',
      fullName: 'Pop Queen',
      profileImageUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 6,
      username: 'classicman',
      password: '',
      email: 'classicman@example.com',
      role: 'User',
      fullName: 'Classic Man',
      profileImageUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 7,
      username: 'hiphophead',
      password: '',
      email: 'hiphophead@example.com',
      role: 'User',
      fullName: 'Hip Hop Head',
      profileImageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 8,
      username: 'countrygal',
      password: '',
      email: 'countrygal@example.com',
      role: 'Celebrity',
      fullName: 'Country Gal',
      profileImageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
      createdAt: DateTime.now(),
    ),
    User(
      id: 9,
      username: 'reggaeking',
      password: '',
      email: 'reggaeking@example.com',
      role: 'Celebrity',
      fullName: 'Reggae King',
      profileImageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
      createdAt: DateTime.now(),
    ),
  ];

  static Future<List<User>> searchUsers(String query) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 500));
    return dummyUsers
        .where((user) => user.fullName.toLowerCase().contains(query.toLowerCase()) ||
            user.username.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }

  static Future<List<Flick>> searchFlicks(String query) async {
    // Dummy likes, comments, categories, hashtags
    final dummyLikes = [
      Like(userId: dummyUsers[0].id.toString(), likedAt: DateTime.now().subtract(const Duration(days: 1))),
      Like(userId: dummyUsers[1].id.toString(), likedAt: DateTime.now().subtract(const Duration(hours: 5))),
      Like(userId: dummyUsers[2].id.toString(), likedAt: DateTime.now().subtract(const Duration(minutes: 30))),
    ];
    final dummyComments = [
      Comment(
        id: 'c1',
        user: dummyUsers[3],
        content: 'Awesome video!',
        likes: 2,
        replies: [
          Comment(
            id: 'c1r1',
            user: dummyUsers[4],
            content: 'Totally agree!',
            likes: 1,
            replies: [],
          ),
        ],
      ),
      Comment(
        id: 'c2',
        user: dummyUsers[5],
        content: 'So funny 😂',
        likes: 3,
        replies: [],
      ),
    ];
    final dummyCategories = ['Music', 'Funny', 'Viral'];
    final dummyHashtags = ['#fun', '#music', '#viral'];
    // Dummy flicks with confirmed working video links and new fields
    final List<Flick> dummyFlicks = [
      Flick(
        id: '1',
        thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32138874/13702933_1440_2534_26fps.mp4',
        title: 'Big Buck Bunny',
        creator: dummyUsers[0],
        views: 1234,
        duration: Duration(minutes: 1, seconds: 0),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Amsterdam, Netherlands',
        timestamp: DateTime.now().subtract(const Duration(days: 1)),
        userRatings: const {'1': 4, '2': 5},
      ),
      Flick(
        id: '2',
        thumbnail: 'https://img.youtube.com/vi/3tmd-ClpJxA/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/9191078/9191078-hd_1080_1920_30fps.mp4',
        title: 'Sample 1MB',
        creator: dummyUsers[1],
        views: 5678,
        duration: Duration(minutes: 2, seconds: 30),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Paris, France',
        timestamp: DateTime.now().subtract(const Duration(days: 2)),
        userRatings: const {}, // unrated
      ),
      Flick(
        id: '3',
        thumbnail: 'https://img.youtube.com/vi/aqz-KE-bpKQ/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/31850424/13568518_1080_1920_24fps.mp4',
        title: 'Sample 10MB',
        creator: dummyUsers[2],
        views: 2345,
        duration: Duration(minutes: 0, seconds: 30),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Tokyo, Japan',
        timestamp: DateTime.now().subtract(const Duration(days: 3)),
        userRatings: const {'1': 3},
      ),
      Flick(
        id: '4',
        thumbnail: 'https://img.youtube.com/vi/2Vv-BfVoq4g/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32332685/13792266_1440_2560_30fps.mp4',
        title: 'LearningContainer',
        creator: dummyUsers[3],
        views: 3456,
        duration: Duration(minutes: 1, seconds: 10),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'New York, USA',
        timestamp: DateTime.now().subtract(const Duration(days: 4)),
        userRatings: const {}, // unrated
      ),
      Flick(
        id: '5',
        thumbnail: 'https://img.youtube.com/vi/9bZkp7q19f0/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32320376/13785526_1440_2560_30fps.mp4',
        title: 'Sample 5MB',
        creator: dummyUsers[4],
        views: 4567,
        duration: Duration(minutes: 0, seconds: 45),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Seoul, South Korea',
        timestamp: DateTime.now().subtract(const Duration(days: 5)),
        userRatings: const {'2': 2, '3': 5},
      ),
      Flick(
        id: '6',
        thumbnail: 'https://img.youtube.com/vi/OPf0YbXqDm0/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/31817090/13556100_1080_1920_60fps.mp4',
        title: 'Sample 2MB',
        creator: dummyUsers[5],
        views: 5678,
        duration: Duration(minutes: 1, seconds: 20),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Rio de Janeiro, Brazil',
        timestamp: DateTime.now().subtract(const Duration(days: 6)),
        userRatings: const {}, // unrated
      ),
      Flick(
        id: '7',
        thumbnail: 'https://img.youtube.com/vi/60ItHLz5WEA/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32197923/13731630_1440_2560_30fps.mp4',
        title: 'Sample 20MB',
        creator: dummyUsers[0],
        views: 6789,
        duration: Duration(minutes: 2, seconds: 0),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'London, UK',
        timestamp: DateTime.now().subtract(const Duration(days: 7)),
        userRatings: const {'1': 1},
      ),
      Flick(
        id: '8',
        thumbnail: 'https://img.youtube.com/vi/CevxZvSJLk8/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/3842573/3842573-uhd_2560_1440_30fps.mp4',
        title: 'Sample 30MB',
        creator: dummyUsers[1],
        views: 7890,
        duration: Duration(minutes: 2, seconds: 30),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Venice, Italy',
        timestamp: DateTime.now().subtract(const Duration(days: 8)),
        userRatings: const {},
      ),
      Flick(
        id: '9',
        thumbnail: 'https://img.youtube.com/vi/ScMzIvxBSi4/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/28754657/12467820_1080_1920_48fps.mp4',
        title: 'Sample 50MB',
        creator: dummyUsers[2],
        views: 8901,
        duration: Duration(minutes: 1, seconds: 15),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Cape Town, South Africa',
        timestamp: DateTime.now().subtract(const Duration(days: 9)),
        userRatings: const {},
      ),
      Flick(
        id: '10',
        thumbnail: 'https://img.youtube.com/vi/2vjPBrBU-TM/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32114960/13691527_1440_2560_60fps.mp4',
        title: 'Sample 100MB',
        creator: dummyUsers[3],
        views: 9012,
        duration: Duration(minutes: 1, seconds: 40),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Dubai, UAE',
        timestamp: DateTime.now().subtract(const Duration(days: 10)),
        userRatings: const {},
      ),
      Flick(
        id: '11',
        thumbnail: 'https://img.youtube.com/vi/uelHwf8o7_U/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/31190177/13323575_1080_1920_50fps.mp4',
        title: 'LearningContainer 2',
        creator: dummyUsers[4],
        views: 10123,
        duration: Duration(minutes: 2, seconds: 10),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Berlin, Germany',
        timestamp: DateTime.now().subtract(const Duration(days: 11)),
        userRatings: const {},
      ),
      Flick(
        id: '12',
        thumbnail: 'https://img.youtube.com/vi/09R8_2nJtjg/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32313700/13782007_1080_1920_100fps.mp4',
        title: 'W3Schools Bunny 2',
        creator: dummyUsers[5],
        views: 11234,
        duration: Duration(minutes: 2, seconds: 50),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Bangkok, Thailand',
        timestamp: DateTime.now().subtract(const Duration(days: 12)),
        userRatings: const {},
      ),
      Flick(
        id: '13',
        thumbnail: 'https://img.youtube.com/vi/3AtDnEC4zak/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32282234/13767019_1440_2560_60fps.mp4',
        title: 'Sample 1MB 2',
        creator: dummyUsers[0],
        views: 12345,
        duration: Duration(minutes: 3, seconds: 0),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Moscow, Russia',
        timestamp: DateTime.now().subtract(const Duration(days: 13)),
        userRatings: const {},
      ),
      Flick(
        id: '14',
        thumbnail: 'https://img.youtube.com/vi/2Vv-BfVoq4g/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/27444986/12146476_1440_2560_30fps.mp4',
        title: 'Sample 10MB 2',
        creator: dummyUsers[1],
        views: 13456,
        duration: Duration(minutes: 3, seconds: 20),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Toronto, Canada',
        timestamp: DateTime.now().subtract(const Duration(days: 14)),
        userRatings: const {},
      ),
      Flick(
        id: '15',
        thumbnail: 'https://img.youtube.com/vi/OPf0YbXqDm0/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32115048/13691643_1440_2560_30fps.mp4',
        title: 'Sample 5MB 2',
        creator: dummyUsers[2],
        views: 14567,
        duration: Duration(minutes: 3, seconds: 40),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Prague, Czech Republic',
        timestamp: DateTime.now().subtract(const Duration(days: 15)),
        userRatings: const {},
      ),
      Flick(
        id: '16',
        thumbnail: 'https://img.youtube.com/vi/60ItHLz5WEA/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32094550/13681469_1440_2560_30fps.mp4',
        title: 'Sample 2MB 2',
        creator: dummyUsers[3],
        views: 15678,
        duration: Duration(minutes: 4, seconds: 0),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Cairo, Egypt',
        timestamp: DateTime.now().subtract(const Duration(days: 16)),
        userRatings: const {},
      ),
      Flick(
        id: '17',
        thumbnail: 'https://img.youtube.com/vi/CevxZvSJLk8/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/27608561/12184920_1920_1080_30fps.mp4',
        title: 'Sample 20MB 2',
        creator: dummyUsers[4],
        views: 16789,
        duration: Duration(minutes: 4, seconds: 20),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Los Angeles, USA',
        timestamp: DateTime.now().subtract(const Duration(days: 17)),
        userRatings: const {},
      ),
      Flick(
        id: '18',
        thumbnail: 'https://img.youtube.com/vi/ScMzIvxBSi4/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/32699365/13940516_1080_1920_60fps.mp4',
        title: 'Sample 30MB 2',
        creator: dummyUsers[5],
        views: 17890,
        duration: Duration(minutes: 4, seconds: 40),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Rome, Italy',
        timestamp: DateTime.now().subtract(const Duration(days: 18)),
        userRatings: const {},
      ),
      Flick(
        id: '19',
        thumbnail: 'https://img.youtube.com/vi/2vjPBrBU-TM/0.jpg',
        flickUrl: 'https://videos.pexels.com/video-files/12594868/12594868-uhd_1440_2560_60fps.mp4',
        title: 'Sample 50MB 2',
        creator: dummyUsers[0],
        views: 18901,
        duration: Duration(minutes: 5, seconds: 0),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Istanbul, Turkey',
        timestamp: DateTime.now().subtract(const Duration(days: 19)),
        userRatings: const {},
      ),
      Flick(
        id: '20',
        thumbnail: 'https://img.youtube.com/vi/uelHwf8o7_U/0.jpg',
        flickUrl: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_100mb.mp4',
        title: 'Sample 100MB 2',
        creator: dummyUsers[1],
        views: 19012,
        duration: Duration(minutes: 5, seconds: 20),
        likes: dummyLikes,
        comments: dummyComments,
        categories: dummyCategories,
        hashtags: dummyHashtags,
        location: 'Santorini, Greece',
        timestamp: DateTime.now().subtract(const Duration(days: 20)),
        userRatings: const {},
      ),
    ];
    await Future.delayed(const Duration(milliseconds: 500));
    return dummyFlicks;
  }

  static final List<Post> dummyPosts = [
    Post(
      id: '1',
      content: 'Beautiful sunset view from Oia.',
      from: dummyUsers[0],
      categories: ['Travel', 'Nature'],
      hashtags: ['#sunset', '#greece', '#travel'],
      timestamp: DateTime.now().subtract(const Duration(days: 1)),
      mediaLink: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      timeAgo: '1d',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[1].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c1', user: dummyUsers[1], content: 'Amazing!', likes: 2, replies: [])],
      location: 'Santorini, Greece',
    ),
    Post(
      id: '2',
      content: 'Eiffel Tower in the morning mist.',
      from: dummyUsers[1],
      categories: ['Travel', 'City'],
      hashtags: ['#paris', '#eiffeltower', '#morning'],
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      mediaLink: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
      timeAgo: '2d',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[2].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c2', user: dummyUsers[2], content: 'So pretty!', likes: 1, replies: [])],
      location: 'Paris, France',
    ),
    Post(
      id: '3',
      content: 'Shibuya crossing at night.',
      from: dummyUsers[2],
      categories: ['Travel', 'Nightlife'],
      hashtags: ['#tokyo', '#shibuya', '#night'],
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      mediaLink: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
      timeAgo: '3d',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[3].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c3', user: dummyUsers[3], content: 'Love Tokyo!', likes: 3, replies: [])],
      location: 'Tokyo, Japan',
    ),
    Post(
      id: '4',
      content: 'Central Park in autumn.',
      from: dummyUsers[3],
      categories: ['Nature', 'City'],
      hashtags: ['#newyork', '#centralpark', '#autumn'],
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      mediaLink: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99',
      timeAgo: '4d',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[4].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c4', user: dummyUsers[4], content: 'So colorful!', likes: 2, replies: [])],
      location: 'New York, USA',
    ),
    Post(
      id: '5',
      content: 'Opera House at dusk.',
      from: dummyUsers[4],
      categories: ['Architecture', 'Travel'],
      hashtags: ['#sydney', '#opera', '#dusk'],
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      mediaLink: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      timeAgo: '5d',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[5].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c5', user: dummyUsers[5], content: 'Iconic!', likes: 1, replies: [])],
      location: 'Sydney, Australia',
    ),
    Post(
      id: '6',
      content: 'Dancing in the streets.',
      from: dummyUsers[5],
      categories: ['Culture', 'Festival'],
      hashtags: ['#riocarnival', '#brazil', '#dance'],
      timestamp: DateTime.now().subtract(const Duration(days: 6)),
      mediaLink: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
      timeAgo: '6d',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[6].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c6', user: dummyUsers[6], content: 'What a vibe!', likes: 2, replies: [])],
      location: 'Rio de Janeiro, Brazil',
    ),
    Post(
      id: '7',
      content: 'Foggy morning on the Thames.',
      from: dummyUsers[6],
      categories: ['Travel', 'City'],
      hashtags: ['#london', '#thames', '#fog'],
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      mediaLink: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[7].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c7', user: dummyUsers[7], content: 'Misty mornings are the best!', likes: 3, replies: [])],
      location: 'London, UK',
    ),
    Post(
      id: '8',
      content: 'Gondola ride through the city.',
      from: dummyUsers[7],
      categories: ['Travel', 'Romance'],
      hashtags: ['#venice', '#gondola', '#romance'],
      timestamp: DateTime.now().subtract(const Duration(days: 8)),
      mediaLink: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[8].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c8', user: dummyUsers[8], content: 'So romantic!', likes: 2, replies: [])],
      location: 'Venice, Italy',
    ),
    Post(
      id: '9',
      content: 'Table Mountain hike.',
      from: dummyUsers[8],
      categories: ['Adventure', 'Nature'],
      hashtags: ['#capetown', '#tablemountain', '#hiking'],
      timestamp: DateTime.now().subtract(const Duration(days: 9)),
      mediaLink: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[0].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c9', user: dummyUsers[0], content: 'Breathtaking view!', likes: 3, replies: [])],
      location: 'Cape Town, South Africa',
    ),
    Post(
      id: '10',
      content: 'La Rambla at sunset.',
      from: dummyUsers[0],
      categories: ['Travel', 'Food'],
      hashtags: ['#barcelona', '#larambla', '#sunset'],
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
      mediaLink: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[1].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c10', user: dummyUsers[1], content: 'Delicious food!', likes: 2, replies: [])],
      location: 'Barcelona, Spain',
    ),
    Post(
      id: '11',
      content: 'Historic graffiti art.',
      from: dummyUsers[1],
      categories: ['Art', 'History'],
      hashtags: ['#berlin', '#graffiti', '#history'],
      timestamp: DateTime.now().subtract(const Duration(days: 11)),
      mediaLink: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[2].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c11', user: dummyUsers[2], content: 'Love this!', likes: 1, replies: [])],
      location: 'Berlin, Germany',
    ),
    Post(
      id: '12',
      content: 'Burj Khalifa at night.',
      from: dummyUsers[2],
      categories: ['Travel', 'Architecture'],
      hashtags: ['#dubai', '#burjkhalifa', '#night'],
      timestamp: DateTime.now().subtract(const Duration(days: 12)),
      mediaLink: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[3].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c12', user: dummyUsers[3], content: 'Stunning!', likes: 2, replies: [])],
      location: 'Dubai, UAE',
    ),
    Post(
      id: '13',
      content: 'Street food and night markets.',
      from: dummyUsers[3],
      categories: ['Food', 'Culture'],
      hashtags: ['#bangkok', '#streetfood', '#nightmarkets'],
      timestamp: DateTime.now().subtract(const Duration(days: 13)),
      mediaLink: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[4].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c13', user: dummyUsers[4], content: 'Yum!', likes: 1, replies: [])],
      location: 'Bangkok, Thailand',
    ),
    Post(
      id: '14',
      content: 'Snowy winter day.',
      from: dummyUsers[4],
      categories: ['Travel', 'Winter'],
      hashtags: ['#moscow', '#winter', '#snow'],
      timestamp: DateTime.now().subtract(const Duration(days: 14)),
      mediaLink: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[5].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c14', user: dummyUsers[5], content: 'Beautiful!', likes: 2, replies: [])],
      location: 'Moscow, Russia',
    ),
    Post(
      id: '15',
      content: 'CN Tower and city lights.',
      from: dummyUsers[5],
      categories: ['Travel', 'City'],
      hashtags: ['#toronto', '#cntower', '#citylights'],
      timestamp: DateTime.now().subtract(const Duration(days: 15)),
      mediaLink: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[6].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c15', user: dummyUsers[6], content: 'Amazing view!', likes: 3, replies: [])],
      location: 'Toronto, Canada',
    ),
    Post(
      id: '16',
      content: 'Old town charm.',
      from: dummyUsers[6],
      categories: ['Travel', 'History'],
      hashtags: ['#prague', '#oldtown', '#charm'],
      timestamp: DateTime.now().subtract(const Duration(days: 16)),
      mediaLink: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[7].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c16', user: dummyUsers[7], content: 'So picturesque!', likes: 2, replies: [])],
      location: 'Prague, Czech Republic',
    ),
    Post(
      id: '17',
      content: 'Ancient wonders.',
      from: dummyUsers[7],
      categories: ['Travel', 'History'],
      hashtags: ['#cairo', '#pyramids', '#ancient'],
      timestamp: DateTime.now().subtract(const Duration(days: 17)),
      mediaLink: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[8].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c17', user: dummyUsers[8], content: 'Incredible!', likes: 1, replies: [])],
      location: 'Cairo, Egypt',
    ),
    Post(
      id: '18',
      content: 'Santa Monica pier.',
      from: dummyUsers[8],
      categories: ['Travel', 'Beach'],
      hashtags: ['#losangeles', '#santamonica', '#beach'],
      timestamp: DateTime.now().subtract(const Duration(days: 18)),
      mediaLink: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[0].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c18', user: dummyUsers[0], content: 'Wish I was there!', likes: 2, replies: [])],
      location: 'Los Angeles, USA',
    ),
    Post(
      id: '19',
      content: 'Historic ruins.',
      from: dummyUsers[0],
      categories: ['Travel', 'History'],
      hashtags: ['#rome', '#colosseum', '#history'],
      timestamp: DateTime.now().subtract(const Duration(days: 19)),
      mediaLink: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99', type: 'image')],
      initialRating: 4,
      likes: [Like(userId: dummyUsers[1].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c19', user: dummyUsers[1], content: 'So much history!', likes: 3, replies: [])],
      location: 'Rome, Italy',
    ),
    Post(
      id: '20',
      content: 'Spices and colors.',
      from: dummyUsers[1],
      categories: ['Travel', 'Market'],
      hashtags: ['#istanbul', '#bazaar', '#spices'],
      timestamp: DateTime.now().subtract(const Duration(days: 20)),
      mediaLink: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      timeAgo: '1w',
      media: [MediaItem(url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb', type: 'image')],
      initialRating: 5,
      likes: [Like(userId: dummyUsers[2].id.toString(), likedAt: DateTime.now())],
      comments: [Comment(id: 'c20', user: dummyUsers[2], content: 'Love the colors!', likes: 2, replies: [])],
      location: 'Istanbul, Turkey',
    ),
  ];

  static Future<List<dynamic>> searchPostsByLocation(String locationQuery) async {
    await Future.delayed(const Duration(milliseconds: 400));
    final posts = dummyPosts
        .where((post) => post.location.toLowerCase().contains(locationQuery.toLowerCase()))
        .toList();
    final flicks = (await searchFlicks(locationQuery))
        .where((flick) => flick.location.toLowerCase().contains(locationQuery.toLowerCase()))
        .toList();
    // Combine and sort by timestamp (for posts) and a pseudo-timestamp for flicks (use a 'timestamp' field if available, else fallback to a default)
    final combined = <Map<String, dynamic>>[];
    for (var post in posts) {
      combined.add({'type': 'post', 'data': post, 'timestamp': post.timestamp});
    }
    for (var flick in flicks) {
      // Use a pseudo timestamp for flicks (e.g., DateTime.now() - index if not available)
      final flickTimestamp = flick is Flick && flick is dynamic && flick.timestamp != null
        ? flick.timestamp
        : DateTime.now();
      combined.add({'type': 'flick', 'data': flick, 'timestamp': flickTimestamp});
    }
    combined.sort((a, b) => b['timestamp'].compareTo(a['timestamp']));
    return combined;
  }

  static Future<List<AudioPost>> searchAudio(String query) async {
    // Dummy audio posts (reuse AudioService dummy data)
    final allAudio = await AudioService.fetchAudioPosts();
    return allAudio.where((audio) =>
      audio.title.toLowerCase().contains(query.toLowerCase()) ||
      audio.description.toLowerCase().contains(query.toLowerCase()) ||
      audio.from.username.toLowerCase().contains(query.toLowerCase())
    ).toList();
  }
}
