spring:
  application:
    name: post-service
  config:
    import: "optional:configserver:http://197.254.53.252:8888"
  datasource:
    url: jdbc:postgresql://197.254.53.252:5432/celebratedb
    username: celebrate
    password: celebrate123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  r2dbc:
    url: r2dbc:postgresql://197.254.53.252:5432/celebratedb
    username: celebrate
    password: celebrate123
  liquibase:
    url: jdbc:postgresql://197.254.53.252:5432/celebratedb
    user: celebrate
    password: celebrate123
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://197.254.53.252:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: 197.254.53.252
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: 8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3
  expiration: 86400000 # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds 