spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://41.89.64.12:8888"
  cloud:
    config:
      fail-fast: true
  datasource:
    url: jdbc:postgresql://41.89.64.12/celebratedb
    username: celebrate
    password: celebrate123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: UserHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: 41.89.64.12:8090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082
  servlet:
    context-path: /

security:
  jwt:
    public-key: classpath:public_key.pem

eureka:
  client:
    service-url:
      defaultZone: http://41.89.64.12:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: 41.89.64.12
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.celebrating.user: DEBUG

kafka:
  topics:
    user-events: user-events