spring:
  application:
    name: auth-service
  config:
    import: "configserver:"
  datasource:
    url: jdbc:postgresql://197.254.53.252:5432/celebratedb?sslmode=disable
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8081
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://197.254.53.252:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: false
    hostname: 197.254.53.252
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

jwt:
  secret: your-secret-key-must-be-at-least-32-characters-long-and-very-secure-123
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.celebrating.auth: DEBUG

cors:
  allowed-origins: 
    - "http://197.254.53.252:*"
    - "http://127.0.0.1:*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowed-headers: "*"
  exposed-headers: 
    - "Authorization"
    - "Content-Type"
  allow-credentials: true
  max-age: 3600
